config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.all
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to post_comments_path, notice: 'Comment sucesfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)

    if @comment.save
      redirect_to posts_path, notice: 'Comment succesfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to posts_path, alert: 'Comment succesfully deleted', status: :see_other
  end

  private

  def comment_params
    params.require(:coment).permit(:author, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:comments).all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post updated succesfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Post succesfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, alert: 'Post succesfully deleted', status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_time(post)
    if post.created_at
      "#{post.created_at.to_date} | #{time_ago_in_words(post.created_at, include_seconds: true)} ago"
    elsif post.updated_at
      post.updated_at.to_date
    end
  end
end

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
  <%= comment.author %>
  <%= comment.content %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="mt-8 sm:mx-auto sm:w-full sm:max-w-xl">
  <div class="space-y-6">
    <%= form_with model: @post do |f| %>

      <%= f.label :title, class: "block text-sm font-medium mt-3" %>
      <div class="mt-2 relative rounded-md shadow-sm">
        <%= f.text_field :title, class:"block w-full border rounded shadow-md" %>
      </div>

      <div>
        <%= f.label :content, class: "block text-sm font-medium mt-3" %>
        <%= f.text_area :content, rows: 15, class: "block w-full border rounded shadow-md" %>
      </div>

      <div>
        <%= f.label :status, class:"block text-sm font-medium mt-3" %>
        <%= f.text_field :status, class:"block w-full border rounded shadow-md" %>
      </div>

      <div>
        <%= f.submit class:"mt-3 bg-sky-300 p-1.5 rounded-lg hover:bg-gray-300 hover:transition-all" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post_with_comments.erb
<div class="mt-8 sm:mx-auto sm:w-full sm:max-w-lg">

  <div class="space-y-6">

    <% @posts.each do |post| %>
      <div>
        <%= link_to post.title, post_path(post), class: 'block font-medium mt-3' %>
      </div>

      <div>
        <%= truncate(post.content, length: 40, separator: '', class:'block text-sm mt-3') %>
      </div>

      <div>
        <%= post.status %>
      </div>

      <div>
        <%= link_to "Read more", post_path(post), class:'text-sky-600 hover:underline hover:text-sm' %>
      </div>

      <div class="text-gray-500 text-sm">
        <%= icon('fa-solid', 'calendar-days') %> 
        <%= post_time(post) %>
      </div>
      <div class=" text-gray-500 text-sm space-y-2">
        <% post.comments.each do |comment| %>
          <div><%= comment.author %></div>
          <div class="mt-2">
            <%= icon('fa-solid', 'comment') %>
            <%= link_to post.comments.count, post_comments_path(post, comment) %> |
            <%= link_to "New comment", new_post_comment_path(post) %>
          </div>
        <% end %>
      </div>

      <hr>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="flex justify-center">
  <h3>Edit <%= @post.title %></h3>
</div>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="w-full min-h[100vh] bg-indigo500 flex flex-col items-center">
  <h3 class=" font-bold text-xl bg-sky-100">Pancho Macias Noob Blog</h3>
  <p class="text-md mb-6">"Another blog web app, for personal use"</p>
</div>

<%= render 'post_with_comments' %>

app/views/posts/new.html.erb
<div class="flex justify-center">
  <h3>New Post</h3>
</div>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="w-full min-h[100vh] flex flex-col items-center">
  <h1 class="font-bold text-lg bg-sky-100"><%= @post.title %></h1>
</div>

<div class="flex flex-col items-center mt-8 sm:mx-auto sm:w-full sm:max-w-3xl">
  <div class="text-center"><%= @post.content %></div>
</div>

<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "New", new_post_path(@post) %>
<%= link_to "Delete", post_path(@post), data: {
  turbo_method: :delete, turbo_confirm: "Are you sure?"
} %>